Doc 4281 Edited code comments in CSDE Kotlin template
corda/CSDE-cordapp-template-kotlin pull request #19
Opened 2022-11-16 14:22 UTC by Niamh25

Code comments edited in CSDE Kotlin template.

2022-11-16 14:55 UTC, colin-hillis requested changes
Few small changes

2022-11-16 14:55 UTC, colin-hillis commented on build.gradle
> +    // Enforced versioning has not been implemented yet, enter a dummy value for now.
Change from:

Enforced versioning has not been implemented yet, enter a dummy value for now.

To:

Enforced versioning has not been implemented yet, so enter a dummy value for now.

2022-11-16 14:55 UTC, colin-hillis commented on build.gradle
> +        // Use a version of Kotlin that will be compatible with the Corda API.
From:

Use a version of Kotlin that will be compatible with the Corda API.

To:

Use a version of Kotlin that is compatible with the Corda API.

2022-11-16 14:55 UTC, colin-hillis commented on build.gradle
> +// Required to build CorDapp modules as OSGi bundles that CPI and CPB files are built on dependencies.
Not a trick question, but were we asked to change this sentence structure? The original sentence works for me better I think, if you change "files are built on" to "files are then built upon".

2022-11-16 14:55 UTC, colin-hillis commented on build.gradle
> +    // Declare a "platform" to use the correct set of dependency versions for the version the
From: "version the..."

To: "version that the..."

2022-11-16 14:55 UTC, colin-hillis commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +// A class contains a message, mark it with @CordaSerializable for Corda to send one virtual node to another.
From: "A class contains a message, mark it with @CordaSerializable for Corda to send one virtual node to another."

To: "Where a class contains a message, mark it with @CordaSerializable to enable Corda to send it from one virtual node to another."

2022-11-16 14:55 UTC, colin-hillis commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +        // Create the message payload uses the MessageClass we defined.
From: Create the message payload uses the MessageClass we defined.

To: Create the message payload using the MessageClass that we defined.

2022-11-16 14:55 UTC, colin-hillis commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +        // The return value of a RPCStartableFlow must always be a String, this string will pass
Does String need to start with a capital? Just checking

After string, put a full stop before starting next sentence (This string will pass......)

2022-11-16 14:55 UTC, colin-hillis commented on src/test/kotlin/com/r3/developers/csdetemplate/MyFirstFlowTest.kt
> +        // We don't assign Bob's virtual node to a value, we don't need it for this particular test.
full stop and new sentence after 'value'

2022-11-16 14:55 UTC, colin-hillis commented on src/test/kotlin/com/r3/developers/csdetemplate/MyFirstFlowTest.kt
> +        // Create Alice's and Bob's virtual nodes, including the Class's of the flows which will be registered on each node.
Not Class's

- Does it need to be capitalized? (unsure myself)  
- Should it not be Classes, as use of ' indicates ownership, which doesn't look to be applicable in this sentence. including the Class of the flows....

2022-11-16 15:30 UTC, AnnaK-R3 commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +            // Retry until we get an "OK", it may move to "Validating upload", "Persisting CPI".
```suggestion
            // Retry until you get an "OK", it may move to "Validating upload", "Persisting CPI".
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +            // Expect the id field to be a string.
```suggestion
            // Expect the ID field to be a string.
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // JsonMarshallingService provides a service for manipulating json
```suggestion
    // JsonMarshallingService provides a service for manipulating JSON
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // FlowMessaging establishes flow sessions between Virtual Nodes which
```suggestion
    // FlowMessaging establishes flow sessions between virtual nodes which
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // MemberLookup looks for information about members of the Virtual Network which
```suggestion
    // MemberLookup looks for information about members of the virtual network which
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // this CorDapp is operates in.
```suggestion
    // this CorDapp operates in.
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +        // Follow what happens in the console or logs
```suggestion
        // Follow what happens in the console or logs.
```

2022-11-16 15:30 UTC, AnnaK-R3 commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +        // Show the requestBody in the logs - establishes the format for starting a flow on corda
```suggestion
        // Show the requestBody in the logs - establishes the format for starting a flow on Corda.
```

2022-11-16 15:45 UTC, Niamh25 reviewed
I implemented these changes!

2022-11-17 09:39 UTC, colin-hillis approved these changes
LGTM - Thanks Niamh

2022-11-25 13:22 UTC, ceebee-dev requested changes

2022-11-25 13:22 UTC, ceebee-dev commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +            // Expect the ID field to be a string.
I think this is better:
// Expect the "id" field to be a string.

"id" is the name of the field, the case matters here.

2022-11-25 13:22 UTC, ceebee-dev commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +        // Check that each identity already exists.
Thinking about it a bit more I think replacing the line 302 with the following makes a bit more sense in the context:
// Create a list of X500 IDs we will not need to create VNodes for.

2022-11-25 13:22 UTC, ceebee-dev commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +            // Retry until you get an "OK", it may move to "Validating upload", "Persisting CPI".
I'm thinking something more like this:
// Retry until you get an "OK"; we may see several other responses before the "OK" response.

2022-11-25 13:22 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +// Where a class contains a message, mark it with @CordaSerializable to enable Corda to send it from one virtual node to another.
I think something like this is better, we're trying to say 2 things here.
// A class used for sending a greeting message between the 2 flows.
// Corda requires all classes used to send data from one virtual node to another to be annotated with @CordaSerializable.

2022-11-25 13:22 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +        // The return value of a RPCStartableFlow must always be a string. This string will pass
I think this might be better as String refers to the class "String", the capital letter is important:
// The return value of a RPCStartableFlow must always be a String. This will be passed

2022-11-25 13:22 UTC, ceebee-dev commented on src/test/kotlin/com/r3/developers/csdetemplate/MyFirstFlowTest.kt
> +        // We don't assign Bob's virtual node to a value. We don't need it for this particular test.
I think the original line 26 is better here because in this case "val" is referring to the val type of a Kotlin variable. It's not being used as a shorter form of the word "value", for instance.

2022-11-25 13:22 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // this CorDapp operates in.
Want to write "provides a service" as we talk about MemberLookup as a "service" .

2022-11-25 13:22 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // sends and receives payloads between them.
We want to write "provides a service" as we refer to FlowMessaging as a service, or define FlowMessaging as a service

2022-12-06 09:46 UTC, ceebee-dev commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +            // Retry until you get an "OK", it may move to "Validating upload", "Persisting CPI".
Please change to the above

2022-12-06 09:47 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +// Where a class contains a message, mark it with @CordaSerializable to enable Corda to send it from one virtual node to another.
please change to the above

2022-12-06 10:47 UTC, ceebee-dev requested changes

2022-12-06 10:47 UTC, ceebee-dev commented on buildSrc/src/main/java/com/r3/csde/CsdeRpcInterface.java
> +        // Check that each identity already exists.
Please change to the following or equivalent:
// Create a list of X500 IDs we will not need to create VNodes for.

2022-12-06 10:47 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // sends and receives payloads between them.
The "provides a service" part is important because we're trying to educate users of the concept of Corda services.

2022-12-06 10:47 UTC, ceebee-dev commented on src/test/kotlin/com/r3/developers/csdetemplate/MyFirstFlowTest.kt
> +        // We don't assign Bob's virtual node to a value. We don't need it for this particular test.
I think we need to be clear here and say either:
"We don't assign Bob's virtual node to a **Kotlin** value."
or
"We don't assign Bob's virtual node to a **val**."

2022-12-06 15:33 UTC, ceebee-dev requested changes

2022-12-06 15:33 UTC, ceebee-dev commented on build.gradle
> +    // Corda API specifies
// Declare a "platform" to use the correct set of dependency versions for the version of 
    // Corda API specified.

2022-12-06 15:33 UTC, ceebee-dev commented on src/main/kotlin/com/r3/developers/csdetemplate/MyFirstFlow.kt
> +    // this CorDapp operates in.
// MemberLookup provides a service for looks up information about members of the virtual network which
    // this CorDapp operates in.
    
    Think of MemberLookup as a "yellow pages" service

2022-12-06 15:51 UTC, ceebee-dev reviewed
LGTM thanks

2022-12-06 15:51 UTC, ceebee-dev approved these changes

2022-12-06 16:10 UTC, merged